"""
Turns the clean CSVs into js/data.js so the dashboard can load them without
a fetch. Re-run this after the scrapers update the data.
"""

import json
import math
import os
import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(BASE, "../js/data.js")

BROADWAY_CLEAN = os.path.join(BASE, "../data/wicked_broadway_weekly_clean.csv")
MOVIE_CLEAN    = os.path.join(BASE, "../data/wicked_domestic_daily_clean.csv")
MOVIE2_CLEAN   = os.path.join(BASE, "../data/wicked2_domestic_daily_clean.csv")


def serialize(val):
    if val is None:
        return None
    if isinstance(val, float) and math.isnan(val):
        return None
    if isinstance(val, (np.integer,)):
        return int(val)
    if isinstance(val, (np.floating,)):
        return None if math.isnan(val) else round(float(val), 2)
    return val


def df_to_js(df, cols):
    records = []
    for _, row in df[cols].iterrows():
        records.append({c: serialize(row[c]) for c in cols})
    return json.dumps(records, separators=(",", ":"))


def main():
    b  = pd.read_csv(BROADWAY_CLEAN)
    m  = pd.read_csv(MOVIE_CLEAN)

    b_cols = [
        "week_ending", "week_number", "broadway_season", "status",
        "weekly_gross", "avg_ticket", "seats_sold", "seats_in_theatre",
        "performances", "previews", "pct_capacity",
    ]
    m_cols = [
        "date", "day_of_week", "day_number", "phase", "rank",
        "daily_gross", "pct_change_yd", "theaters", "avg_per_theater",
        "cumulative_gross",
    ]

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by python/generate_data_js.py — do not edit manually\n\n")
        f.write(f"const BROADWAY_DATA = {df_to_js(b, b_cols)};\n\n")
        f.write(f"const MOVIE1_DATA = {df_to_js(m, m_cols)};  // Wicked (2024)\n\n")

        if os.path.exists(MOVIE2_CLEAN):
            m2 = pd.read_csv(MOVIE2_CLEAN)
            f.write(f"const MOVIE2_DATA = {df_to_js(m2, m_cols)};  // Wicked: For Good (2025)\n")
        else:
            f.write("const MOVIE2_DATA = [];  // Wicked: For Good (2025) — not yet scraped\n")

    print(f"Written: {OUT}")
    print(f"  Broadway rows : {len(b)}")
    print(f"  Movie 1 rows  : {len(m)}")
    if os.path.exists(MOVIE2_CLEAN):
        m2 = pd.read_csv(MOVIE2_CLEAN)
        print(f"  Movie 2 rows  : {len(m2)}")


if __name__ == "__main__":
    main()
